### ISSUE TITLE
This is the error: SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by smalike** [jmcriffey/babel-istanbul#70]
$ npm run coverage
"test-cov": "istanbul cover node_modules/mocha/bin/_mocha -- --recursive --timeout 500000 test/ --compilers js:babel-register",

```
node_modules\.bin\babel-istanbul:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] 
```

**Comment by jmcriffey** [comment]
Is this error happening in Windows? I'm not sure about the gotchas with Istanbul and Windows, but here is the official documentation: https://github.com/gotwarlost/istanbul#usage-on-windows.

**Comment by danday74** [comment]
I had this problem, fixed by using WIN approach below ...

LINUX "./node_modules/.bin/istanbul test ./node_modules/.bin/_mocha -- --recursive -R spec"
WIN   "./node_modules/.bin/istanbul test ./node_modules/mocha/bin/_mocha -- --recursive -R spec"

See https://github.com/gotwarlost/istanbul/issues/13#issuecomment-32001190 for more details

**Comment by jbarngr** [comment]
@danday74 Your solution worked for me also. Thank you.
