### ISSUE TITLE
Uncovered branch in leading multiline comment

### ISSUE THREAD

**Issue by just-paja** [jmcriffey/babel-istanbul#79]
There seems to be some problem when covering code with combination of `import`, `spread operator` and `multiline comments`. Istanbul will report else branch uncovered on the leading multiline comment.

I prepared [example repository](https://github.com/just-paja/babel-istanbul-coverage-fail-example) where the problem is reproducable and also contains examples that are working.

![CLI](https://raw.githubusercontent.com/just-paja/babel-istanbul-coverage-fail-example/master/images/babel-istanbul-cli.png)

![HTML](https://raw.githubusercontent.com/just-paja/babel-istanbul-coverage-fail-example/master/images/babel-istanbul-html.png)

**Comment by jmcriffey** [comment]
This is likely due to the source map generated by babel. Could you post a screenshot of the code generated by babel for that file?

**Comment by just-paja** [comment]
@jmcriffey, I added [babel output](https://github.com/just-paja/babel-istanbul-coverage-fail-example/blob/master/dist/notCovered.js) to the example repo.

**Comment by jmcriffey** [comment]
[This line](https://github.com/just-paja/babel-istanbul-coverage-fail-example/blob/master/dist/notCovered.js#L14) is definitely the culprit. What usually happens in these cases are a feature gets added and the source map gets broken in some small way. If the source map doesn't reflect the code correctly, then this tool cannot do its job. With that being said, there are three possible solutions:

1. Use the `babel-runtime` transform in your babel config. Using this transform will use babel helper function calls instead of injecting all of that logic in every file. I think this is the best solution, as it also optimizes your file size. 

2. Look at babel and figure out how to fix the sourcemap for `toConsumableArray`. Then open a PR for the fix in their repo.

3. Try different versions (older and newer) of babel and its presets. This could be a sourcemap issue with the newest versions, or it could be and old issue that is already fixed in a more current version.

**Comment by just-paja** [comment]
@jmcriffey, thank you for explanation. I think that this could become part of the projects README.

**Comment by just-paja** [comment]
I tried the proposed solution number 1 and it worked. Thanks. I'll keep [the example repository](https://github.com/just-paja/babel-istanbul-coverage-fail-example) archived for other people to see the problem and the solution.
